version: '3'
 
services:
  cornercase:
    build:
      context: .
    ports:
      - "80:8000"
    volumes:
      - .:/CornerCase
    command: >
      sh -c "python3 manage.py makemigrations
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000 --insecure"
  redis:
    image: redis:alpine
    command: redis-server
  celery:
    restart: always
    build:
      context: .
    command: celery -A CornerCase worker -l info
    volumes:
      - .:/CornerCase
      - /var/run/docker.sock:/var/run/docker.sock
    # environment:
    #   - DB_HOST=db
    #   - DB_NAME=app
    #   - DB_USER=postgres
    #   - DB_PASS=supersecretpassword
    depends_on:
      - redis
      - cornercase