# Generated by Django 3.2.13 on 2022-06-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguages',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('compileCommand', models.TextField(default=0)),
                ('executeCommand', models.TextField()),
            ],
        ),
    ]
