# Generated by Django 4.0.5 on 2022-06-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executable',
            fields=[
                ('status', models.CharField(max_length=255)),
                ('userCode', models.TextField()),
                ('userLanguage', models.IntegerField()),
                ('generatorCode', models.TextField()),
                ('generatorLanguage', models.IntegerField()),
                ('editorialCode', models.TextField()),
                ('editorialLanguage', models.IntegerField()),
                ('newfiled', models.CharField(max_length=1)),
                ('queueNo', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('compileCommand', models.TextField(null=True)),
                ('executeCommand', models.TextField(null=True)),
                ('fileExtension', models.CharField(default='.cpp', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generatedTest', models.TextField()),
                ('userOutput', models.TextField()),
                ('editorialoutput', models.TextField()),
                ('passed', models.BooleanField(default=False)),
                ('executable', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Tester.executable')),
            ],
        ),
    ]
