# Generated by Django 3.2.13 on 2022-06-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgrammingLanguages',
            new_name='ProgrammingLanguage',
        ),
    ]
