# Generated by Django 4.0.5 on 2022-06-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executable',
            name='newfiled',
        ),
        migrations.AddField(
            model_name='executable',
            name='datetime',
            field=models.DateTimeField(default=None),
        ),
    ]
