# Generated by Django 3.2.13 on 2022-06-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0002_rename_programminglanguages_programminglanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executable',
            fields=[
                ('status', models.CharField(max_length=255)),
                ('userCode', models.TextField()),
                ('userLanguage', models.IntegerField()),
                ('generatorCode', models.TextField()),
                ('generatorLanguge', models.IntegerField()),
                ('editorialCode', models.TextField()),
                ('editorialLanguage', models.IntegerField()),
                ('queueNo', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
