# Generated by Django 3.2.13 on 2022-06-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0003_executable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generatedTest', models.TextField()),
                ('userOutput', models.TextField()),
                ('editorialoutput', models.TextField()),
                ('passed', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='executable',
            old_name='generatorLanguge',
            new_name='generatorLanguage',
        ),
        migrations.AddField(
            model_name='executable',
            name='testCases',
            field=models.ManyToManyField(to='Tester.Test'),
        ),
    ]
