# Generated by Django 4.0.5 on 2022-06-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0003_alter_executable_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='passed',
        ),
        migrations.AddField(
            model_name='test',
            name='verdict',
            field=models.CharField(default='Running', max_length=25),
        ),
    ]
