# Generated by Django 4.0.5 on 2022-06-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0004_auto_20220610_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='fileExtension',
            field=models.CharField(default='.cpp', max_length=255),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='compileCommand',
            field=models.TextField(default=''),
        ),
    ]
