# Generated by Django 4.0.5 on 2022-06-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0005_programminglanguage_fileextension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='executeCommand',
            field=models.TextField(default=''),
        ),
    ]
