# Generated by Django 4.0.5 on 2022-06-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0005_programminglanguage_dockerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='editorialCPUtime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='generatorCPUtime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='userCPUtime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='executable',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
