# Generated by Django 4.0.5 on 2022-06-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0006_alter_programminglanguage_executecommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='compileCommand',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='executeCommand',
            field=models.TextField(null=True),
        ),
    ]
