# Generated by Django 4.0.5 on 2022-06-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0007_alter_programminglanguage_compilecommand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
