# Generated by Django 4.0.5 on 2022-06-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0008_alter_test_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executable',
            name='testCases',
        ),
        migrations.AddField(
            model_name='test',
            name='executable',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Tester.executable'),
        ),
    ]
